/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ua_khpi_oop_lab16_NativeTemperatureConverter */

#ifndef _Included_ua_khpi_oop_lab16_NativeTemperatureConverter
#define _Included_ua_khpi_oop_lab16_NativeTemperatureConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ua_khpi_oop_lab16_NativeTemperatureConverter
 * Method:    celsiusToFahrenheit
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_ua_khpi_oop_lab16_NativeTemperatureConverter_celsiusToFahrenheit
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
